services:
  # --- COLLECTEUR (Le cœur qui remplit la base) ---
  cyber-monitor-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor_collector
    volumes:
      - ../../code_monitoring:/app/code_monitoring
      - ../../Data:/app/data
    networks:
      - monitoring-net
    environment:
      - PYTHONUNBUFFERED=1 
    command: python /app/code_monitoring/sonde/collecteur.py
    restart: always
  # --- DASHBOARD (L'interface visuelle) ---
  cyber-dashboard:
    build:
      context: . 
    container_name: monitor_dashboard
    ports:
      - "8050:8050" 
    volumes:
      - ../../code_monitoring:/app/code_monitoring
      - ../../Data:/app/data
    networks:
      - monitoring-net
    environment:
      - PYTHONUNBUFFERED=1
    # On lance bien app.py (le serveur Flask)
    command: python /app/code_monitoring/dashboard/app.py 
    depends_on:
      - cyber-monitor-collector
    restart: always

  # --- PARC SIMULÉ : MACHINES LINUX ---
  linux-srv-1:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-01
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  linux-srv-2:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-02
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  # --- PARC SIMULÉ : POSTES WINDOWS ---
  win-wkst-1:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-01
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  win-wkst-2:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-02
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  # --- SERVEUR WINDOWS CRITIQUE ---
  win-srv-indispensable:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=SRV-WIN-CORE
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py
    restart: always

networks:
  monitoring-net:
    driver: bridge