services:
  # --- SERVEUR CENTRAL DE MONITORING ---
  cyber-monitor-center:
   build:
    context: .
    dockerfile: Dockerfile

   volumes:
     - ../../code_monitoring:/app/code_monitoring
     - ../../Data:/app/data
   networks:
      - monitoring-net
   environment:
      - PYTHONUNBUFFERED=1 

   command: python /app/code_monitoring/sonde/collecteur.py

  # --- PARC SIMULÉ : MACHINES LINUX ---
  linux-srv-1:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-01
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  linux-srv-2:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-02
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  # --- PARC SIMULÉ : POSTES WINDOWS ---
  win-wkst-1:
    build: .
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-01
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  win-wkst-2:
    build: .
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-02
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py

  # --- SERVEUR WINDOWS CRITIQUE (Haute Disponibilité) ---
  win-srv-indispensable:
    build: .
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=SRV-WIN-CORE
    volumes:
      - ./scripts:/scripts
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py
    restart: always

# --- RÉSEAU VIRTUEL ---
networks:
  monitoring-net:
    driver: bridge