services:
  # --- COLLECTEUR ---
  cyber-monitor-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor_collector
    volumes:
      - ../../code_monitoring:/app/code_monitoring
      - ../../Data:/app/data
       
    networks:
      - monitoring-net
    environment:
      - PYTHONUNBUFFERED=1 
    # VERROU : Attend l'initialisation
    command: sh -c "while [ ! -f /app/data/.initialized ]; do sleep 3; done; exec python /app/code_monitoring/sonde/collecteur.py"
    restart: always

  # --- DASHBOARD ---
  cyber-dashboard:
    build:
      context: . 
    container_name: monitor_dashboard
    ports:
      - "8050:8050" 
    volumes:
      - ../../code_monitoring:/app/code_monitoring
      - ../../Data:/app/data
      - ../../Data/Logs:/app/data/logs 
      - ../..:/infrastructure
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    env_file:
      - .env
    environment:
      - IS_MASTER_CONSOLE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/code_monitoring 
    # VERROU ACTIF : Le dashboard agit comme un chien de garde et abat les conteneurs demarres manuellement
    command: >
      sh -c "
      if [ ! -f /app/data/.initialized ]; then
        echo '[SYSTEM] Premier demarrage. Verrouillage actif...';
        while [ ! -f /app/data/.initialized ]; do
          docker stop monitor_collector linux-srv-1 linux-srv-2 win-wkst-1 win-wkst-2 win-srv-indispensable > /dev/null 2>&1 || true;
          sleep 2;
        done;
      fi;
      echo '[SYSTEM] Lancement du Dashboard...';
      exec python /app/code_monitoring/dashboard/app.py
      "
    depends_on:
      - cyber-monitor-collector
    restart: always

  # --- PARC SIMULÉ : MACHINES LINUX ---
  linux-srv-1:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-01
    env_file:
      - .env
    container_name: linux-srv-1
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    # VERROU : Attend l'initialisation
    command: sh -c "while [ ! -f /app/Data/.initialized ]; do sleep 3; done; exec python /scripts/simu_agent.py"
    restart: always

  linux-srv-2:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-02
    env_file:
      - .env
    container_name: linux-srv-2
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: sh -c "while [ ! -f /app/Data/.initialized ]; do sleep 3; done; exec python /scripts/simu_agent.py"
    restart: always

  # --- PARC SIMULÉ : POSTES WINDOWS ---
  win-wkst-1:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    env_file:
      - .env
    container_name: win-wkst-1
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-01
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: sh -c "while [ ! -f /app/Data/.initialized ]; do sleep 3; done; exec python /scripts/simu_agent.py"
    restart: always

  win-wkst-2:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    env_file:
      - .env
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-02
    container_name: win-wkst-2
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: sh -c "while [ ! -f /app/Data/.initialized ]; do sleep 3; done; exec python /scripts/simu_agent.py"
    restart: always

  # --- SERVEUR WINDOWS CRITIQUE ---
  win-srv-indispensable:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    env_file:
      - .env
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=SRV-WIN-CORE
    container_name: win-srv-indispensable
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: sh -c "while [ ! -f /app/Data/.initialized ]; do sleep 3; done; exec python /scripts/simu_agent.py"
    restart: always

networks:
  monitoring-net:
    driver: bridge