FROM python:3.9-slim-bullseye

RUN apt-get update && apt-get install -y sqlite3 wget apt-transport-https software-properties-common && rm -rf /var/lib/apt/lists/*

RUN wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" && dpkg -i packages-microsoft-prod.deb && apt-get update && apt-get install -y powershell && rm -rf /var/lib/apt/lists/* && rm packages-microsoft-prod.deb

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .