services:
  # --- COLLECTEUR (Le coeur qui remplit la base) ---
  cyber-monitor-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor_collector
    volumes:
      - ../../code_monitoring:/app/code_monitoring
      - ../../Data:/app/data
    networks:
      - monitoring-net
    environment:
      - PYTHONUNBUFFERED=1 
    command: python /app/code_monitoring/sonde/collecteur.py
    restart: always

  # --- DASHBOARD (L'interface visuelle) ---
  cyber-dashboard:
    build:
      context: . 
    container_name: monitor_dashboard
    ports:
      - "8050:8050" 
    volumes:
      - ../../code_monitoring:/app/code_monitoring
      - ../../Data:/app/data
      - ../..:/infrastructure # Donne accès à tout le projet pour le backup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    env_file:
      - .env
    environment:
      - IS_MASTER_CONSOLE=1 # Active le piège du shell vers la console
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/code_monitoring 
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET}
    command: python /app/code_monitoring/dashboard/app.py 
    depends_on:
      - cyber-monitor-collector
    restart: always

  # --- PARC SIMULÉ : MACHINES LINUX ---
  linux-srv-1:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-01
    container_name: linux-srv-1
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py
    restart: on-failure

  linux-srv-2:
    build: .
    environment:
      - OS_TYPE=Linux
      - MACHINE_NAME=SRV-LINUX-02
    container_name: linux-srv-2
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py
    restart: on-failure

  # --- PARC SIMULÉ : POSTES WINDOWS ---
  win-wkst-1:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    container_name: win-wkst-1
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-01
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py
    restart: on-failure

  win-wkst-2:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=WKST-WIN-02
    container_name: win-wkst-2
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py
    restart: on-failure

  # --- SERVEUR WINDOWS CRITIQUE ---
  win-srv-indispensable:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    tty: true
    environment:
      - OS_TYPE=Windows
      - MACHINE_NAME=SRV-WIN-CORE
    container_name: win-srv-indispensable
    volumes:
      - ./scripts:/scripts
      - ../../Data:/app/Data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-net
    command: python /scripts/simu_agent.py
    restart: always

networks:
  monitoring-net:
    driver: bridge